Fix win-trace broken by tracegz.py
Gets invoked on win-trace resulting in errors like:

    FileNotFoundError: [Errno 2] No such file or directory: '..\\..\\src\\tests\\restricted_traces\\BindGeneratesResourceTest_Textures_ES2_Vulkan_SwiftShader\\BindGeneratesResourceTest_Textures_ES2_Vulkan_SwiftShader.json'

https://ci.chromium.org/ui/p/angle/builders/ci/win-trace/3788/overview

Bug: b/276742336
Change-Id: I2d86cdbcbc0286746e535a4b19f4d4b547b5783f
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/4436590
Commit-Queue: Cody Northrop <cnorthrop@google.com>
Reviewed-by: Cody Northrop <cnorthrop@google.com>
Auto-Submit: Roman Lavrov <romanl@google.com>