Revert "Support constant folding of exponential built-ins"
Causing compile errors on Android:

../../third_party/angle/src/compiler/translator/IntermNode.cpp:1309:62: error: use of undeclared identifier 'log2f'
                else if (!foldFloatTypeUnary(unionArray[i], &log2f, infoSink, &tempConstArray[i]))

This reverts commit 1623a1b90f24cd1afd8839c0726ad276a887fbda.

Change-Id: If9c45aea85801eb11e7d1513b4183ec11289d2f3
Reviewed-on: https://chromium-review.googlesource.com/266154
Reviewed-by: Jamie Madill <jmadill@chromium.org>
Tested-by: Jamie Madill <jmadill@chromium.org>