Revert "Avoid a copy in TextureStorage11::setData"
Fails on the Windows builders:

https://build.chromium.org/p/chromium.gpu.fyi/builders/GPU%20Win%20Builder/builds/42201

e:\b\build\slave\gpu_win_builder\build\src\third_party\angle\src\libangle\renderer\d3d\d3d11\load_functions_table_autogen.cpp(787) : error C2440: 'return' : cannot convert from 'const std::map<GLenum,rx::LoadImageFunction,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>' to 'const std::map<GLenum,rx::d3d11::LoadImageFunctionInfo,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>> &'
        with
        [
            _Kty=GLuint
,            _Ty=rx::LoadImageFunction
        ]
        and
        [
            _Kty=GLuint
,            _Ty=rx::d3d11::LoadImageFunctionInfo
        ]
        Reason: cannot convert from 'const std::map<GLenum,rx::LoadImageFunction,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>' to 'const std::map<GLenum,rx::d3d11::LoadImageFunctionInfo,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>'
        with
        [
            _Kty=GLuint
,            _Ty=rx::LoadImageFunction
        ]
        and
        [
            _Kty=GLuint
,            _Ty=rx::d3d11::LoadImageFunctionInfo
        ]
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

This reverts commit 52d3e43b66478b07d26c95a5511d4132cec26000.

Change-Id: I83774ea09ccbb2b92ff609714e1c7201beb775bc
Reviewed-on: https://chromium-review.googlesource.com/326540
Reviewed-by: Jamie Madill <jmadill@chromium.org>