Revert "Use nullptr consistently in TIntermConstantUnion::fold"
Part of a chain causing compile errors on Mac. Example:

../../third_party/angle/src/compiler/translator/IntermNode.cpp:1216:89: error: no member named 'sin' in namespace 'std'; did you mean 'sinf'?

http://build.chromium.org/p/chromium.gpu.fyi/builders/GPU%20Linux%20Builder/builds/33747

This reverts commit 72ed20d4bb5a5c55d9909d6cc9b7a0e89e4a81a2.

Change-Id: Ia6119f6081b3184deef3deef25b9e3f43ff2e2a6
Reviewed-on: https://chromium-review.googlesource.com/265586
Reviewed-by: Jamie Madill <jmadill@chromium.org>
Tested-by: Jamie Madill <jmadill@chromium.org>