Fix build failure in chrome due to unused function
Chrome build fails on a warning:
"../../third_party/angle/src/compiler/translator/QualifierTypes.cpp:30:6:
error: unused function 'IsInvariantCorrect' [-Werror,-Wunused-function]"

BUG=angleproject:1442

Change-Id: If2fea0d90e9cd789c3a6449881794082f3e98afd
Reviewed-on: https://chromium-review.googlesource.com/381201
Reviewed-by: Olli Etuaho <oetuaho@nvidia.com>
Commit-Queue: Olli Etuaho <oetuaho@nvidia.com>